import { ArrowRight, Download, LayoutTemplate, ScanSearch, Sparkles, WandSparkles } from 'lucide-react';
import React, { useState } from 'react';
import { Link } from 'react-router-dom';

const steps = [
  {number: '01', icon: WandSparkles, title: 'Write clearly', description: 'Turn rough notes into confident, achievement-led language.'},
  {number: '02', icon: ScanSearch, title: 'Tailor quickly', description: 'Use the role context to focus your strongest experience.'},
  {number: '03', icon: Download, title: 'Send proudly', description: 'Export a clean, readable resume when it is ready.'},
];

const showcases = [
  {id: 'writing', eyebrow: 'AI-assisted writing', title: 'Your best work, in your own voice.', body: 'Start with the details you already know. ResuAI helps shape them into concise, outcome-focused bullets without taking over the story.', tone: 'mint'},
  {id: 'matching', eyebrow: 'Role matching', title: 'A resume that knows where it is going.', body: 'Compare your content with a job description and get a clearer view of the language and strengths to bring forward.', tone: 'amber'},
  {id: 'design', eyebrow: 'Design system', title: 'Make the layout feel like you.', body: 'Choose a focused starting point, change the density, order your sections, and pick a color theme that fits your direction.', tone: 'violet'},
];

const ShowcaseVisual = ({id, tone}) => {
  if (id === 'matching') return <div className={`showcase-visual showcase-${tone} rounded-3xl border p-5`}><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Role match</span><span className="rounded-full bg-amber-100 px-2.5 py-1 text-[10px] font-semibold text-amber-800">Good alignment</span></div><div className="mt-7 flex items-center gap-6"><div className="relative flex size-32 items-center justify-center rounded-full border-[10px] border-amber-100"><div className="absolute inset-[-10px] rounded-full border-[10px] border-amber-500 border-b-transparent border-l-transparent rotate-[-38deg]" /><span className="text-3xl font-semibold text-slate-900">78%</span></div><div className="space-y-3 text-xs text-slate-600"><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-green-500" /> 8 strengths found</p><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-amber-500" /> 3 keywords to review</p><p className="flex items-center gap-2"><span className="size-2 rounded-full bg-slate-300" /> 1 section to refine</p></div></div></div>;
  if (id === 'design') return <div className={`showcase-visual showcase-${tone} rounded-3xl border p-5`}><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Theme studio</span><span className="text-xs font-medium text-slate-500">Evergreen</span></div><div className="mt-6 grid grid-cols-[0.65fr_1fr] gap-4"><div className="space-y-2"><div className="rounded-xl border border-green-300 bg-green-50 p-3"><div className="h-2 w-14 rounded-full bg-green-700" /><div className="mt-2 h-1.5 w-20 rounded-full bg-green-200" /></div><div className="rounded-xl border border-slate-200 bg-white p-3"><div className="h-2 w-16 rounded-full bg-slate-800" /><div className="mt-2 h-1.5 w-20 rounded-full bg-slate-200" /></div><div className="rounded-xl border border-slate-200 bg-white p-3"><div className="h-2 w-12 rounded-full bg-slate-800" /><div className="mt-2 h-1.5 w-16 rounded-full bg-slate-200" /></div></div><div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="h-2 w-24 rounded-full bg-slate-900" /><div className="mt-4 h-1.5 w-full rounded-full bg-green-500" /><div className="mt-4 space-y-2"><div className="h-1.5 w-full rounded-full bg-slate-200" /><div className="h-1.5 w-10/12 rounded-full bg-slate-200" /><div className="h-1.5 w-8/12 rounded-full bg-slate-200" /></div><div className="mt-6 flex gap-1.5"><span className="size-5 rounded-full bg-green-700" /><span className="size-5 rounded-full bg-amber-500" /><span className="size-5 rounded-full bg-slate-800" /></div></div></div></div>;
  return <div className={`showcase-visual showcase-${tone} rounded-3xl border p-5`}><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-violet-100 text-violet-700"><Sparkles className="size-4" /></span><div><p className="text-xs font-semibold text-slate-900">Rewrite suggestion</p><p className="text-[10px] text-slate-500">Experience section</p></div></div><div className="mt-6 rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs leading-5 text-slate-500">Worked with cross-functional teams to improve a product experience.</p><div className="my-4 h-px bg-slate-100" /><p className="text-xs font-medium leading-5 text-slate-800">Partnered with 4 teams to simplify onboarding and lift activation by 24%.</p><button type="button" className="mt-4 rounded-lg bg-green-700 px-3 py-2 text-[10px] font-semibold text-white">Use suggestion</button></div></div>;
};

const Features = () => {
  const [active, setActive] = useState('writing');
  const selected = showcases.find((item) => item.id === active) || showcases[0];

  return <section id="features" className="scroll-mt-10 bg-[#f7f7f2] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="animate-rise-in max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-green-700">The workflow</p><h2 className="mt-5 max-w-xl text-4xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-5xl">Everything you need to move with clarity.</h2><p className="mt-5 max-w-lg text-base leading-7 text-slate-600">A considered workspace for the parts of applying that usually feel scattered.</p></div><div className="mt-14 grid gap-3 border-y border-slate-200 py-5 md:grid-cols-3">{steps.map(({number, icon: Icon, title, description}) => <div key={number} className="interactive-card group flex gap-4 rounded-2xl p-4"><span className="text-xs font-semibold text-green-700">{number}</span><div>{React.createElement(Icon, {className: 'size-5 text-slate-800 transition group-hover:text-green-700'})}<h3 className="mt-3 font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{description}</p></div></div>)}</div><div className="mt-24 grid items-start gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-green-700">Designed around the work</p><h2 className="mt-4 max-w-lg text-4xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-5xl">Less fiddling. More forward motion.</h2><p className="mt-5 max-w-md text-base leading-7 text-slate-600">The product stays close to the document, so every suggestion, design decision, and improvement has a visible result.</p><div className="mt-8 space-y-2">{showcases.map((item) => <button key={item.id} type="button" onClick={() => setActive(item.id)} className={`interactive-card flex w-full items-center justify-between rounded-2xl border p-4 text-left ${active === item.id ? 'border-green-300 bg-white shadow-sm' : 'border-transparent hover:border-slate-200 hover:bg-white/70'}`} aria-pressed={active === item.id}><span><span className="block text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">{item.eyebrow}</span><span className="mt-1 block font-semibold text-slate-900">{item.title}</span></span><ArrowRight className={`size-4 transition ${active === item.id ? 'text-green-700' : 'text-slate-300 group-hover:text-slate-600'}`} /></button>)}</div></div><div className="animate-slide-right"><ShowcaseVisual id={selected.id} tone={selected.tone} /><div className="mt-4 flex items-center justify-between px-1"><p className="max-w-sm text-sm leading-6 text-slate-500">{selected.body}</p><Link to="/app?state=register" className="hidden items-center gap-2 text-sm font-semibold text-green-700 transition hover:gap-3 sm:flex">Open studio <ArrowRight className="size-4" /></Link></div></div></div></div></section>;
};

export default Features;
